Repository ausaccessfed/reporting-service, pull requests merged in 2024-09, with the labels that each got.

#551 chore(deps): upgrade rspec-rails 6.1.3 -> 6.1.5
  Gemfile
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#564 chore(deps): upgrade rspec-rails 6.1.3 -> 7.0.0
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#566 chore(deps): upgrade rspec-rails 6.1.5 -> 7.0.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#568 chore(deps): upgrade eslint 9.9.1 -> 9.10.0
  package.json
  yarn.lock
Labels: dependencies, devDependencies

#569 chore(deps): upgrade rspec-rails 6.1.5 -> 7.0.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#570 chore(deps): upgrade rubocop-rspec 3.0.4 -> 3.0.5
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#573 chore(deps): upgrade kernel-devel 5.14.0-427.33.1.el9_4 -> 5.14.0-427.35.1.el9_4
  Dockerfile
  app/controllers/favicons_controller.rb
  config/routes.rb
Labels: dependencies, dockerDependencies

#579 chore(deps): upgrade puma 6.4.2 -> 6.4.3
  Gemfile.lock
Labels: dependencies

#582 chore(deps): upgrade cuprite 0.15 -> 0.15.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#578 chore(deps): upgrade simplecov-console 0.9.1 -> 0.9.2
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#580 chore(deps): upgrade eslint 9.10.0 -> 9.11.1
  package.json
  yarn.lock
Labels: dependencies, devDependencies

#576 chore(deps): upgrade rubocop-performance 1.21.1 -> 1.22.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#549 chore(deps): upgrade shoulda-matchers 6.3.0 -> 6.4.0
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#583 Improve local dev
  .gitignore
  bin/setup
  config/application.rb
  public/.keep
Labels: technical quality

#494 chore(deps): upgrade ruby 3.3.1 -> 3.3.5
  .ruby-version
Labels: dependencies

#577 chore(deps): upgrade dotenv 3.1.2 -> 3.1.4
  Gemfile.lock
Labels: dependencies, devDependencies

#584 chore(deps): upgrade kernel-devel 5.14.0-427.35.1.el9_4 -> 5.14.0-427.37.1.el9_4
  Dockerfile
Labels: dependencies, dockerDependencies

#585 chore(deps): upgrade chromium 129.0.6668.58-1.el9 -> 129.0.6668.70-1.el9
  Dockerfile
Labels: dependencies, dockerDependencies
