Repository ausaccessfed/reporting-service, pull requests merged in 2024-07, with the labels that each got.

#508 chore(deps): upgrade chromium 126.0.6478.114-1.el9 -> 126.0.6478.126-1.el9
  Dockerfile
Labels: dependencies, dockerDependencies

#479 chore(deps): upgrade rmagick 5.4.4 -> 5.5.0
  Gemfile.lock
Labels: dependencies

#483 chore(deps): upgrade jbuilder 2.11.5 -> 2.12.0
  Gemfile.lock
Labels: dependencies

#347 chore(deps): upgrade activerecord-session_store 2.0.0 -> 2.1.0
  Gemfile.lock
Labels: dependencies

#482 chore(deps): upgrade aws-sdk-sqs 1.70.0 -> 1.80.0
  Gemfile.lock
Labels: dependencies

#357 chore(deps): upgrade rubocop-rspec 2.24.1 -> 2.31.0
  .rubocop.yml
  Gemfile.lock
  app/reports/federation_growth_report.rb
  spec/features/administrator_reports_spec.rb
  spec/features/automated_report_instances_spec.rb
  spec/features/automated_reports_spec.rb
  spec/features/compliance_reports_spec.rb
  spec/features/federation_reports_spec.rb
  spec/features/identity_provider_reports_spec.rb
  spec/features/login_spec.rb
  spec/features/service_provider_reports_spec.rb
  spec/features/subscriber_reports_dashboard_spec.rb
  spec/jobs/create_automated_report_instances_spec.rb
  spec/support/subscriber_reports_controller.rb
  spec/support/subscription_features.rb
  spec/support/subscription_with_nil_target_features.rb
Labels: dependencies

#471 chore(deps): upgrade sentry-ruby monorepo 5.16.1 -> 5.18.1
  Gemfile.lock
Labels: dependencies

#436 chore(deps): upgrade rubocop-factory_bot 2.25.1 -> 2.26.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#356 chore(deps): upgrade rubocop-rails 2.19.1 -> 2.25.1
  Gemfile.lock
Labels: dependencies

#511 chore(deps): upgrade kernel-devel 5.14.0-427.22.1.el9_4 -> 5.14.0-427.24.1.el9_4
  Dockerfile
Labels: dependencies, dockerDependencies

#515 chore(deps): upgrade eslint 9.6.0 -> 9.7.0
  package.json
  yarn.lock
Labels: dependencies, devDependencies

#516 chore(deps): upgrade faker 3.4.1 -> 3.4.2
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#520 chore(deps): upgrade chromium 126.0.6478.126-1.el9 -> 126.0.6478.182-1.el9
  Dockerfile
Labels: dependencies, dockerDependencies

#521 Upgrade rexml to 3.3.2
  Gemfile.lock
Labels: security

#525 chore(deps): upgrade kernel-devel 5.14.0-427.24.1.el9_4 -> 5.14.0-427.26.1.el9_4
  Dockerfile
Labels: dependencies, dockerDependencies

#528 chore(deps): upgrade eslint 9.7.0 -> 9.8.0
  package.json
  yarn.lock
Labels: dependencies, devDependencies

#529 chore(deps): upgrade cuprite 0.15 -> 0.15.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#530 chore(deps): upgrade cuprite 0.15 -> 0.15.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies
