Repository ausaccessfed/reporting-service, pull requests merged in 2024-08, with the labels that each got.

#539 Upgrade rexml to 3.3.4
  Gemfile.lock
Labels: security

#540 chore(deps): upgrade chromium 126.0.6478.182-1.el9 -> 127.0.6533.88-2.el9
  Dockerfile
Labels: dependencies, dockerDependencies

#546 chore(deps): upgrade shoulda-matchers 6.2.0 -> 6.3.0
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#545 chore(deps): upgrade eslint 9.8.0 -> 9.9.0
  package.json
  yarn.lock
Labels: dependencies, devDependencies

#547 chore(deps): upgrade cuprite 0.15 -> 0.15.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#548 chore(deps): upgrade yum
  Dockerfile
Labels: dependencies, dockerDependencies

#513 chore(deps): upgrade rubocop-rspec 3.0.2 -> 3.0.4
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#554 chore(deps): upgrade brakeman 6.1.2 -> 6.2.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#555 chore(deps): upgrade eslint 9.9.0 -> 9.9.1
  package.json
  yarn.lock
Labels: dependencies, devDependencies

#562 chore(deps): upgrade kernel-devel 5.14.0-427.31.1.el9_4 -> 5.14.0-427.33.1.el9_4
  Dockerfile
Labels: dependencies, dockerDependencies
