Repository ausaccessfed/reporting-service, pull requests merged in 2024-05, with the labels that each got.

#468 chore(deps): upgrade launchy/launchy 2.5.2 -> 3.0.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#474 chore(deps): upgrade rspec-rails/rspec-rails 6.1.1 -> 6.1.2
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#473 chore(deps): upgrade shoulda-matchers/shoulda-matchers 6.1.0 -> 6.2.0
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#486 chore(deps): upgrade yum
  Dockerfile
Labels: dependencies, dockerDependencies

#490 Remove parallel-prettier
  Rakefile
  package.json
  yarn.lock
Labels: technical quality

#491 chore(deps): upgrade kernel-devel/kernel-devel 5.14.0-427.16.1.el9_4 -> 5.14.0-427.18.1.el9_4
  Dockerfile
Labels: dependencies, dockerDependencies

#493 chore(deps): upgrade faker/faker 3.3.1 -> 3.4.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#481 chore(deps): upgrade ruby/ruby 3.3.0 -> 3.3.1
  .ruby-version
Labels: dependencies
