Repository ausaccessfed/reporting-service, pull requests merged in 2025-01, with the labels that each got.

#645 Update Dockerfile dependencies
  Dockerfile
Labels: technical quality

#644 Remove Guard dev tooling
  Gemfile
  Gemfile.lock
  Guardfile
  README.md
Labels: technical quality

#632 chore(deps): upgrade cuprite 0.15 -> 0.15.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#638 chore(deps): upgrade dotenv 3.1.4 -> 3.1.7
  Gemfile.lock
Labels: dependencies, devDependencies

#642 chore(deps): upgrade pry 0.15.0 -> 0.15.2
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#633 chore(deps): upgrade eslint 9.15.0 -> 9.17.0
  package.json
  yarn.lock
Labels: dependencies, devDependencies

#641 chore(deps): upgrade rack-test 2.1.0 -> 2.2.0
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#630 chore(deps): upgrade lint
  package.json
  yarn.lock
Labels: dependencies, devDependencies

#629 chore(deps): upgrade aws-sdk-sqs 1.87.0 -> 1.89.0
  Gemfile.lock
Labels: dependencies

#637 chore(deps): upgrade prometheus_exporter 2.1.1 -> 2.2.0
  Gemfile.lock
Labels: dependencies

#628 chore(deps): upgrade puma 6.4.3 -> 6.5.0
  Gemfile.lock
Labels: dependencies

#631 chore(deps): upgrade rubocop 1.68.0 -> 1.69.2
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#639 chore(deps): upgrade rubocop-rspec 3.2.0 -> 3.3.0
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#622 chore(deps): upgrade rubocop-performance 1.22.1 -> 1.23.0
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#627 chore(deps): upgrade rspec-rails 6.1.5 -> 7.1.0
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#646 Update bundler to bundled version
  .github/workflows/deploy.yml
  Dockerfile
  Gemfile.lock
Labels: technical quality

#650 chore(deps): upgrade rubocop-performance 1.23.0 -> 1.23.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies

#649 chore(deps): upgrade cuprite 0.15 -> 0.15.1
  Gemfile.lock
Labels: dependencies, testDependencies, devDependencies
